In [79]:
arr <- array(rep(1:16, each=3), c(3,4,4))
arr

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    1    2    3    4
[3,]    1    2    3    4

, , 2

     [,1] [,2] [,3] [,4]
[1,]    5    6    7    8
[2,]    5    6    7    8
[3,]    5    6    7    8

, , 3

     [,1] [,2] [,3] [,4]
[1,]    9   10   11   12
[2,]    9   10   11   12
[3,]    9   10   11   12

, , 4

     [,1] [,2] [,3] [,4]
[1,]   13   14   15   16
[2,]   13   14   15   16
[3,]   13   14   15   16

In [78]:
arr[1,,]
arr[2,,]
arr[3,,]

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [75]:
# arr2 <- arr  1:3
arr2 <- arr + 1:3
arr2[1,,]
arr2[2,,]
arr2[3,,]

[,1] [,2] [,3] [,4]
[1,] 2    6    10   14  
[2,] 3    7    11   15  
[3,] 4    8    12   16  
[4,] 5    9    13   17

[,1] [,2] [,3] [,4]
[1,] 3     7   11   15  
[2,] 4     8   12   16  
[3,] 5     9   13   17  
[4,] 6    10   14   18

[,1] [,2] [,3] [,4]
[1,] 4     8   12   16  
[2,] 5     9   13   17  
[3,] 6    10   14   18  
[4,] 7    11   15   19

In [81]:
seq(0, 2*pi, length.out=40)

[1] 0.0000000 0.1611073 0.3222146 0.4833219 0.6444293 0.8055366 0.9666439
 [8] 1.1277512 1.2888585 1.4499658 1.6110732 1.7721805 1.9332878 2.0943951
[15] 2.2555024 2.4166097 2.5777170 2.7388244 2.8999317 3.0610390 3.2221463
[22] 3.3832536 3.5443609 3.7054683 3.8665756 4.0276829 4.1887902 4.3498975
[29] 4.5110048 4.6721122 4.8332195 4.9943268 5.1554341 5.3165414 5.4776487
[36] 5.6387560 5.7998634 5.9609707 6.1220780 6.2831853

In [82]:
0.7785 * exp(1i*(seq(0, 2*pi, length.out=40)))

[1]  0.7785000+0.0000000i  0.7684186+0.1248802i  0.7384356+0.2465260i
 [4]  0.6893275+0.3617870i  0.6223662+0.4676779i  0.5392859+0.5614561i
 [7]  0.4422384+0.6406929i  0.3337372+0.7033362i  0.2165923+0.7477633i
[10]  0.0938378+0.7728239i -0.0313470+0.7778686i -0.1557200+0.7627670i
[13] -0.2760599+0.7279101i -0.3892500+0.6742008i -0.4923587+0.6030300i
[16] -0.5827156+0.5162410i -0.6579805+0.4160816i -0.7162040+0.3051460i
[19] -0.7558782+0.1863072i -0.7759756+0.0626432i -0.7759756-0.0626432i
[22] -0.7558782-0.1863072i -0.7162040-0.3051460i -0.6579805-0.4160816i
[25] -0.5827156-0.5162410i -0.4923587-0.6030300i -0.3892500-0.6742008i
[28] -0.2760599-0.7279101i -0.1557200-0.7627670i -0.0313470-0.7778686i
[31]  0.0938378-0.7728239i  0.2165923-0.7477633i  0.3337372-0.7033362i
[34]  0.4422384-0.6406929i  0.5392859-0.5614561i  0.6223662-0.4676779i
[37]  0.6893275-0.3617870i  0.7384356-0.2465260i  0.7684186-0.1248802i
[40]  0.7785000-0.0000000i